# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import drone_pb2 as drone__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in drone_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DroneControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCommand = channel.unary_unary(
                '/drone.DroneControl/SendCommand',
                request_serializer=drone__pb2.CommandRequest.SerializeToString,
                response_deserializer=drone__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ListDrones = channel.unary_unary(
                '/drone.DroneControl/ListDrones',
                request_serializer=drone__pb2.Empty.SerializeToString,
                response_deserializer=drone__pb2.DroneList.FromString,
                _registered_method=True)


class DroneControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCommand(self, request, context):
        """Envia comando a um drone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDrones(self, request, context):
        """Lista drones disponíveis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DroneControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=drone__pb2.CommandRequest.FromString,
                    response_serializer=drone__pb2.CommandResponse.SerializeToString,
            ),
            'ListDrones': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDrones,
                    request_deserializer=drone__pb2.Empty.FromString,
                    response_serializer=drone__pb2.DroneList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drone.DroneControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drone.DroneControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DroneControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.DroneControl/SendCommand',
            drone__pb2.CommandRequest.SerializeToString,
            drone__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDrones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drone.DroneControl/ListDrones',
            drone__pb2.Empty.SerializeToString,
            drone__pb2.DroneList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
