# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drone.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'drone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64rone.proto\x12\x05\x64rone\"\x07\n\x05\x45mpty\"3\n\x0e\x43ommandRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"3\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\tDroneInfo\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"-\n\tDroneList\x12 \n\x06\x64rones\x18\x01 \x03(\x0b\x32\x10.drone.DroneInfo2z\n\x0c\x44roneControl\x12<\n\x0bSendCommand\x12\x15.drone.CommandRequest\x1a\x16.drone.CommandResponse\x12,\n\nListDrones\x12\x0c.drone.Empty\x1a\x10.drone.DroneListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_COMMANDREQUEST']._serialized_start=31
  _globals['_COMMANDREQUEST']._serialized_end=82
  _globals['_COMMANDRESPONSE']._serialized_start=84
  _globals['_COMMANDRESPONSE']._serialized_end=135
  _globals['_DRONEINFO']._serialized_start=137
  _globals['_DRONEINFO']._serialized_end=182
  _globals['_DRONELIST']._serialized_start=184
  _globals['_DRONELIST']._serialized_end=229
  _globals['_DRONECONTROL']._serialized_start=231
  _globals['_DRONECONTROL']._serialized_end=353
# @@protoc_insertion_point(module_scope)
